services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # depends_on:
    #   - db

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: exampleuser
  #     POSTGRES_PASSWORD: examplepassword
  #     POSTGRES_DB: exampledb
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
